<?php

namespace Appleton\Taxes\Countries\US\NewYork\NewYorkMetropolitanCommuterTransportationMobility\V20190101;

use Appleton\Taxes\Countries\US\NewYork\NewYorkMetropolitanCommuterTransportationMobility\NewYorkMetropolitanCommuterTransportationMobility as BaseNewYorkMetropolitanCommuterTransportationMobility;

class NewYorkMetropolitanCommuterTransportationMobility extends BaseNewYorkMetropolitanCommuterTransportationMobility
{
    const TAX_RATE = 0.0034;

}
