<?php

use Appleton\Taxes\Models\TaxArea;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class InsertOhioSchoolDistrictTaxes extends Migration
{
    private const CLASSES = [
        'Ada EVSD' => Appleton\Taxes\Countries\US\Ohio\AdaEVSDTax\AdaEVSDTax::class,
        'Anna LSD' => Appleton\Taxes\Countries\US\Ohio\AnnaLSDTax\AnnaLSDTax::class,
        'Ansonia LSD' => Appleton\Taxes\Countries\US\Ohio\AnsoniaLSDTax\AnsoniaLSDTax::class,
        'Antwerp LSD' => Appleton\Taxes\Countries\US\Ohio\AntwerpLSDTax\AntwerpLSDTax::class,
        'Arcadia LSD' => Appleton\Taxes\Countries\US\Ohio\ArcadiaLSDTax\ArcadiaLSDTax::class,
        'Arcanum-Butler LSD' => Appleton\Taxes\Countries\US\Ohio\ArcanumButlerLSDTax\ArcanumButlerLSDTax::class,
        'Arlington LSD' => Appleton\Taxes\Countries\US\Ohio\ArlingtonLSDTax\ArlingtonLSDTax::class,
        'Athens CSD' => Appleton\Taxes\Countries\US\Ohio\AthensCSDTax\AthensCSDTax::class,
        'Ayersville LSD' => Appleton\Taxes\Countries\US\Ohio\AyersvilleLSDTax\AyersvilleLSDTax::class,
        'Bellevue CSD' => Appleton\Taxes\Countries\US\Ohio\BellevueCSDTax\BellevueCSDTax::class,
        'Berkshire LSD' => Appleton\Taxes\Countries\US\Ohio\BerkshireLSDTax\BerkshireLSDTax::class,
        'Berne-Union LSD' => Appleton\Taxes\Countries\US\Ohio\BerneUnionLSDTax\BerneUnionLSDTax::class,
        'Bethel LSD' => Appleton\Taxes\Countries\US\Ohio\BethelLSDTax\BethelLSDTax::class,
        'Bexley CSD' => Appleton\Taxes\Countries\US\Ohio\BexleyCSDTax\BexleyCSDTax::class,
        'Big Walnut LSD' => Appleton\Taxes\Countries\US\Ohio\BigWalnutLSDTax\BigWalnutLSDTax::class,
        'Bloom-Carroll LSD' => Appleton\Taxes\Countries\US\Ohio\BloomCarrollLSDTax\BloomCarrollLSDTax::class,
        'Bluffton EVSD' => Appleton\Taxes\Countries\US\Ohio\BlufftonEVSDTax\BlufftonEVSDTax::class,
        'Botkins LSD' => Appleton\Taxes\Countries\US\Ohio\BotkinsLSDTax\BotkinsLSDTax::class,
        'Bowling Green CSD' => Appleton\Taxes\Countries\US\Ohio\BowlingGreenCSDTax\BowlingGreenCSDTax::class,
        'Bradford EVSD' => Appleton\Taxes\Countries\US\Ohio\BradfordEVSDTax\BradfordEVSDTax::class,
        'Bryan CSD' => Appleton\Taxes\Countries\US\Ohio\BryanCSDTax\BryanCSDTax::class,
        'Buckeye Central LSD' => Appleton\Taxes\Countries\US\Ohio\BuckeyeCentralLSDTax\BuckeyeCentralLSDTax::class,
        'Buckeye Valley LSD' => Appleton\Taxes\Countries\US\Ohio\BuckeyeValleyLSDTax\BuckeyeValleyLSDTax::class,
        'Canal Winchester LSD' => Appleton\Taxes\Countries\US\Ohio\CanalWinchesterLSDTax\CanalWinchesterLSDTax::class,
        'Cardington-Lincoln LSD' => Appleton\Taxes\Countries\US\Ohio\CardingtonLincolnLSDTax\CardingtonLincolnLSDTax::class,
        'Carey EVSD' => Appleton\Taxes\Countries\US\Ohio\CareyEVSDTax\CareyEVSDTax::class,
        'Carlisle LSD' => Appleton\Taxes\Countries\US\Ohio\CarlisleLSDTax\CarlisleLSDTax::class,
        'Cedar Cliff LSD' => Appleton\Taxes\Countries\US\Ohio\CedarCliffLSDTax\CedarCliffLSDTax::class,
        'Celina CSD' => Appleton\Taxes\Countries\US\Ohio\CelinaCSDTax\CelinaCSDTax::class,
        'Centerburg LSD' => Appleton\Taxes\Countries\US\Ohio\CenterburgLSDTax\CenterburgLSDTax::class,
        'Central LSD' => Appleton\Taxes\Countries\US\Ohio\CentralLSDTax\CentralLSDTax::class,
        'Chippewa LSD' => Appleton\Taxes\Countries\US\Ohio\ChippewaLSDTax\ChippewaLSDTax::class,
        'Circleville CSD' => Appleton\Taxes\Countries\US\Ohio\CirclevilleCSDTax\CirclevilleCSDTax::class,
        'Clear Fork Valley LSD' => Appleton\Taxes\Countries\US\Ohio\ClearForkValleyLSDTax\ClearForkValleyLSDTax::class,
        'Clermont-Northeastern LSD' =>
        Appleton\Taxes\Countries\US\Ohio\ClermontNortheasternLSDTax\ClermontNortheasternLSDTax::class,
        'Cloverleaf LSD' => Appleton\Taxes\Countries\US\Ohio\CloverleafLSDTax\CloverleafLSDTax::class,
        'Clyde-Green Springs EVSD' => Appleton\Taxes\Countries\US\Ohio\ClydeGreenSpringsEVSDTax\ClydeGreenSpringsEVSDTax::class,
        'Coldwater EVSD' => Appleton\Taxes\Countries\US\Ohio\ColdwaterEVSDTax\ColdwaterEVSDTax::class,
        'Colonel Crawford LSD' => Appleton\Taxes\Countries\US\Ohio\ColonelCrawfordLSDTax\ColonelCrawfordLSDTax::class,
        'Columbiana EVSD' => Appleton\Taxes\Countries\US\Ohio\ColumbianaEVSDTax\ColumbianaEVSDTax::class,
        'Columbus Grove LSD' => Appleton\Taxes\Countries\US\Ohio\ColumbusGroveLSDTax\ColumbusGroveLSDTax::class,
        'Continental LSD' => Appleton\Taxes\Countries\US\Ohio\ContinentalLSDTax\ContinentalLSDTax::class,
        'Cory-Rawson LSD' => Appleton\Taxes\Countries\US\Ohio\CoryRawsonLSDTax\CoryRawsonLSDTax::class,
        'Covington EVSD' => Appleton\Taxes\Countries\US\Ohio\CovingtonEVSDTax\CovingtonEVSDTax::class,
        'Crestline EVSD' => Appleton\Taxes\Countries\US\Ohio\CrestlineEVSDTax\CrestlineEVSDTax::class,
        'Crestview LSD' => Appleton\Taxes\Countries\US\Ohio\CrestviewLSDTax\CrestviewLSDTax::class,
        'Crestview LSD' => Appleton\Taxes\Countries\US\Ohio\CrestviewLSDTax\CrestviewLSDTax::class,
        'Dalton LSD' => Appleton\Taxes\Countries\US\Ohio\DaltonLSDTax\DaltonLSDTax::class,
        'Danville LSD' => Appleton\Taxes\Countries\US\Ohio\DanvilleLSDTax\DanvilleLSDTax::class,
        'Defiance CSD' => Appleton\Taxes\Countries\US\Ohio\DefianceCSDTax\DefianceCSDTax::class,
        'Eastwood LSD' => Appleton\Taxes\Countries\US\Ohio\EastwoodLSDTax\EastwoodLSDTax::class,
        'Eaton CSD' => Appleton\Taxes\Countries\US\Ohio\EatonCSDTax\EatonCSDTax::class,
        'Edgerton LSD' => Appleton\Taxes\Countries\US\Ohio\EdgertonLSDTax\EdgertonLSDTax::class,
        'Edon-Northwest LSD' => Appleton\Taxes\Countries\US\Ohio\EdonNorthwestLSDTax\EdonNorthwestLSDTax::class,
        'Elgin LSD' => Appleton\Taxes\Countries\US\Ohio\ElginLSDTax\ElginLSDTax::class,
        'Elmwood LSD' => Appleton\Taxes\Countries\US\Ohio\ElmwoodLSDTax\ElmwoodLSDTax::class,
        'Evergreen LSD' => Appleton\Taxes\Countries\US\Ohio\EvergreenLSDTax\EvergreenLSDTax::class,
        'Fairbanks LSD' => Appleton\Taxes\Countries\US\Ohio\FairbanksLSDTax\FairbanksLSDTax::class,
        'Fairborn CSD' => Appleton\Taxes\Countries\US\Ohio\FairbornCSDTax\FairbornCSDTax::class,
        'Fairfield Union LSD' => Appleton\Taxes\Countries\US\Ohio\FairfieldUnionLSDTax\FairfieldUnionLSDTax::class,
        'Fairlawn LSD' => Appleton\Taxes\Countries\US\Ohio\FairlawnLSDTax\FairlawnLSDTax::class,
        'Fort Loramie LSD' => Appleton\Taxes\Countries\US\Ohio\FortLoramieLSDTax\FortLoramieLSDTax::class,
        'Fort Recovery LSD' => Appleton\Taxes\Countries\US\Ohio\FortRecoveryLSDTax\FortRecoveryLSDTax::class,
        'Franklin Monroe LSD' => Appleton\Taxes\Countries\US\Ohio\FranklinMonroeLSDTax\FranklinMonroeLSDTax::class,
        'Fremont CSD' => Appleton\Taxes\Countries\US\Ohio\FremontCSDTax\FremontCSDTax::class,
        'Gibsonburg EVSD' => Appleton\Taxes\Countries\US\Ohio\GibsonburgEVSDTax\GibsonburgEVSDTax::class,
        'Gorham Fayette LSD' => Appleton\Taxes\Countries\US\Ohio\GorhamFayetteLSDTax\GorhamFayetteLSDTax::class,
        'Goshen LSD' => Appleton\Taxes\Countries\US\Ohio\GoshenLSDTax\GoshenLSDTax::class,
        'Greeneview LSD' => Appleton\Taxes\Countries\US\Ohio\GreeneviewLSDTax\GreeneviewLSDTax::class,
        'Greenfield EVSD' => Appleton\Taxes\Countries\US\Ohio\GreenfieldEVSDTax\GreenfieldEVSDTax::class,
        'Greenville CSD' => Appleton\Taxes\Countries\US\Ohio\GreenvilleCSDTax\GreenvilleCSDTax::class,
        'Hardin Northern LSD' => Appleton\Taxes\Countries\US\Ohio\HardinNorthernLSDTax\HardinNorthernLSDTax::class,
        'Hardin-Houston LSD' => Appleton\Taxes\Countries\US\Ohio\HardinHoustonLSDTax\HardinHoustonLSDTax::class,
        'Hicksville EVSD' => Appleton\Taxes\Countries\US\Ohio\HicksvilleEVSDTax\HicksvilleEVSDTax::class,
        'Highland LSD' => Appleton\Taxes\Countries\US\Ohio\HighlandLSDTax\HighlandLSDTax::class,
        'Hillsboro CSD' => Appleton\Taxes\Countries\US\Ohio\HillsboroCSDTax\HillsboroCSDTax::class,
        'Hillsdale LSD' => Appleton\Taxes\Countries\US\Ohio\HillsdaleLSDTax\HillsdaleLSDTax::class,
        'Holgate LSD' => Appleton\Taxes\Countries\US\Ohio\HolgateLSDTax\HolgateLSDTax::class,
        'Hopewell-Loudon LSD' => Appleton\Taxes\Countries\US\Ohio\HopewellLoudonLSDTax\HopewellLoudonLSDTax::class,
        'Jackson Center LSD' => Appleton\Taxes\Countries\US\Ohio\JacksonCenterLSDTax\JacksonCenterLSDTax::class,
        'Jefferson LSD' => Appleton\Taxes\Countries\US\Ohio\JeffersonLSDTax\JeffersonLSDTax::class,
        'Jennings LSD' => Appleton\Taxes\Countries\US\Ohio\JenningsLSDTax\JenningsLSDTax::class,
        'Johnstown-Monroe LSD' => Appleton\Taxes\Countries\US\Ohio\JohnstownMonroeLSDTax\JohnstownMonroeLSDTax::class,
        'Jonathan Alder LSD' => Appleton\Taxes\Countries\US\Ohio\JonathanAlderLSDTax\JonathanAlderLSDTax::class,
        'Kalida LSD' => Appleton\Taxes\Countries\US\Ohio\KalidaLSDTax\KalidaLSDTax::class,
        'Kenton CSD' => Appleton\Taxes\Countries\US\Ohio\KentonCSDTax\KentonCSDTax::class,
        'Lakota LSD' => Appleton\Taxes\Countries\US\Ohio\LakotaLSDTax\LakotaLSDTax::class,
        'Lancaster CSD' => Appleton\Taxes\Countries\US\Ohio\LancasterCSDTax\LancasterCSDTax::class,
        'Leipsic LSD' => Appleton\Taxes\Countries\US\Ohio\LeipsicLSDTax\LeipsicLSDTax::class,
        'Liberty Center LSD' => Appleton\Taxes\Countries\US\Ohio\LibertyCenterLSDTax\LibertyCenterLSDTax::class,
        'Liberty Union-Thurston LSD' =>
        Appleton\Taxes\Countries\US\Ohio\LibertyUnionThurstonLSDTax\LibertyUnionThurstonLSDTax::class,
        'Liberty-Benton LSD' => Appleton\Taxes\Countries\US\Ohio\LibertyBentonLSDTax\LibertyBentonLSDTax::class,
        'Licking Valley LSD' => Appleton\Taxes\Countries\US\Ohio\LickingValleyLSDTax\LickingValleyLSDTax::class,
        'Logan Elm LSD' => Appleton\Taxes\Countries\US\Ohio\LoganElmLSDTax\LoganElmLSDTax::class,
        'London CSD' => Appleton\Taxes\Countries\US\Ohio\LondonCSDTax\LondonCSDTax::class,
        'Loudonville-Perrysville EVSD' =>
        Appleton\Taxes\Countries\US\Ohio\LoudonvillePerrysvilleEVSDTax\LoudonvillePerrysvilleEVSDTax::class,
        'Madison LSD' => Appleton\Taxes\Countries\US\Ohio\MadisonLSDTax\MadisonLSDTax::class,
        'McComb LSD' => Appleton\Taxes\Countries\US\Ohio\McCombLSDTax\McCombLSDTax::class,
        'Mechanicsburg EVSD' => Appleton\Taxes\Countries\US\Ohio\MechanicsburgEVSDTax\MechanicsburgEVSDTax::class,
        'Miami East LSD' => Appleton\Taxes\Countries\US\Ohio\MiamiEastLSDTax\MiamiEastLSDTax::class,
        'Millcreek-West Unity LSD' => Appleton\Taxes\Countries\US\Ohio\MillcreekWestUnityLSDTax\MillcreekWestUnityLSDTax::class,
        'Miller City-New Cleveland LSD' =>
        Appleton\Taxes\Countries\US\Ohio\MillerCityNewClevelandLSDTax\MillerCityNewClevelandLSDTax::class,
        'Milton-Union EVSD' => Appleton\Taxes\Countries\US\Ohio\MiltonUnionEVSDTax\MiltonUnionEVSDTax::class,
        'Minster LSD' => Appleton\Taxes\Countries\US\Ohio\MinsterLSDTax\MinsterLSDTax::class,
        'Mississinawa Valley LSD' => Appleton\Taxes\Countries\US\Ohio\MississinawaValleyLSDTax\MississinawaValleyLSDTax::class,
        'Mohawk LSD' => Appleton\Taxes\Countries\US\Ohio\MohawkLSDTax\MohawkLSDTax::class,
        'Monroeville LSD' => Appleton\Taxes\Countries\US\Ohio\MonroevilleLSDTax\MonroevilleLSDTax::class,
        'Montpelier EVSD' => Appleton\Taxes\Countries\US\Ohio\MontpelierEVSDTax\MontpelierEVSDTax::class,
        'Mount Gilead EVSD' => Appleton\Taxes\Countries\US\Ohio\MountGileadEVSDTax\MountGileadEVSDTax::class,
        'National Trail LSD' => Appleton\Taxes\Countries\US\Ohio\NationalTrailLSDTax\NationalTrailLSDTax::class,
        'New Bremen LSD' => Appleton\Taxes\Countries\US\Ohio\NewBremenLSDTax\NewBremenLSDTax::class,
        'New Knoxville LSD' => Appleton\Taxes\Countries\US\Ohio\NewKnoxvilleLSDTax\NewKnoxvilleLSDTax::class,
        'New Lebanon LSD' => Appleton\Taxes\Countries\US\Ohio\NewLebanonLSDTax\NewLebanonLSDTax::class,
        'New London LSD' => Appleton\Taxes\Countries\US\Ohio\NewLondonLSDTax\NewLondonLSDTax::class,
        'New Miami LSD' => Appleton\Taxes\Countries\US\Ohio\NewMiamiLSDTax\NewMiamiLSDTax::class,
        'New Riegel LSD' => Appleton\Taxes\Countries\US\Ohio\NewRiegelLSDTax\NewRiegelLSDTax::class,
        'Newark CSD' => Appleton\Taxes\Countries\US\Ohio\NewarkCSDTax\NewarkCSDTax::class,
        'Newton LSD' => Appleton\Taxes\Countries\US\Ohio\NewtonLSDTax\NewtonLSDTax::class,
        'North Baltimore LSD' => Appleton\Taxes\Countries\US\Ohio\NorthBaltimoreLSDTax\NorthBaltimoreLSDTax::class,
        'North Fork LSD' => Appleton\Taxes\Countries\US\Ohio\NorthForkLSDTax\NorthForkLSDTax::class,
        'North Union LSD' => Appleton\Taxes\Countries\US\Ohio\NorthUnionLSDTax\NorthUnionLSDTax::class,
        'Northeastern LSD' => Appleton\Taxes\Countries\US\Ohio\NortheasternLSDTax\NortheasternLSDTax::class,
        'Northmor LSD' => Appleton\Taxes\Countries\US\Ohio\NorthmorLSDTax\NorthmorLSDTax::class,
        'Northwest LSD' => Appleton\Taxes\Countries\US\Ohio\NorthwestLSDTax\NorthwestLSDTax::class,
        'Northwestern LSD' => Appleton\Taxes\Countries\US\Ohio\NorthwesternLSDTax\NorthwesternLSDTax::class,
        'Northwestern LSD' => Appleton\Taxes\Countries\US\Ohio\NorthwesternLSDTax\NorthwesternLSDTax::class,
        'Northwood LSD' => Appleton\Taxes\Countries\US\Ohio\NorthwoodLSDTax\NorthwoodLSDTax::class,
        'Norwalk CSD' => Appleton\Taxes\Countries\US\Ohio\NorwalkCSDTax\NorwalkCSDTax::class,
        'Norwayne LSD' => Appleton\Taxes\Countries\US\Ohio\NorwayneLSDTax\NorwayneLSDTax::class,
        'Oberlin CSD' => Appleton\Taxes\Countries\US\Ohio\OberlinCSDTax\OberlinCSDTax::class,
        'Old Fort LSD' => Appleton\Taxes\Countries\US\Ohio\OldFortLSDTax\OldFortLSDTax::class,
        'Otsego LSD' => Appleton\Taxes\Countries\US\Ohio\OtsegoLSDTax\OtsegoLSDTax::class,
        'Ottawa-Glandorf LSD' => Appleton\Taxes\Countries\US\Ohio\OttawaGlandorfLSDTax\OttawaGlandorfLSDTax::class,
        'Ottoville LSD' => Appleton\Taxes\Countries\US\Ohio\OttovilleLSDTax\OttovilleLSDTax::class,
        'Pandora-Gilboa LSD' => Appleton\Taxes\Countries\US\Ohio\PandoraGilboaLSDTax\PandoraGilboaLSDTax::class,
        'Parkway LSD' => Appleton\Taxes\Countries\US\Ohio\ParkwayLSDTax\ParkwayLSDTax::class,
        'Patrick Henry LSD' => Appleton\Taxes\Countries\US\Ohio\PatrickHenryLSDTax\PatrickHenryLSDTax::class,
        'Paulding EVSD' => Appleton\Taxes\Countries\US\Ohio\PauldingEVSDTax\PauldingEVSDTax::class,
        'Perrysburg EVSD' => Appleton\Taxes\Countries\US\Ohio\PerrysburgEVSDTax\PerrysburgEVSDTax::class,
        'Pettisville LSD' => Appleton\Taxes\Countries\US\Ohio\PettisvilleLSDTax\PettisvilleLSDTax::class,
        'Pickerington LSD' => Appleton\Taxes\Countries\US\Ohio\PickeringtonLSDTax\PickeringtonLSDTax::class,
        'Piqua CSD' => Appleton\Taxes\Countries\US\Ohio\PiquaCSDTax\PiquaCSDTax::class,
        'Plymouth-Shiloh LSD' => Appleton\Taxes\Countries\US\Ohio\PlymouthShilohLSDTax\PlymouthShilohLSDTax::class,
        'Preble Shawnee LSD' => Appleton\Taxes\Countries\US\Ohio\PrebleShawneeLSDTax\PrebleShawneeLSDTax::class,
        'Reynoldsburg CSD' => Appleton\Taxes\Countries\US\Ohio\ReynoldsburgCSDTax\ReynoldsburgCSDTax::class,
        'Ridgemont LSD' => Appleton\Taxes\Countries\US\Ohio\RidgemontLSDTax\RidgemontLSDTax::class,
        'Riverdale LSD' => Appleton\Taxes\Countries\US\Ohio\RiverdaleLSDTax\RiverdaleLSDTax::class,
        'Riverside LSD' => Appleton\Taxes\Countries\US\Ohio\RiversideLSDTax\RiversideLSDTax::class,
        'Ross LSD' => Appleton\Taxes\Countries\US\Ohio\RossLSDTax\RossLSDTax::class,
        'Russia LSD' => Appleton\Taxes\Countries\US\Ohio\RussiaLSDTax\RussiaLSDTax::class,
        'Sebring LSD' => Appleton\Taxes\Countries\US\Ohio\SebringLSDTax\SebringLSDTax::class,
        'Seneca East LSD' => Appleton\Taxes\Countries\US\Ohio\SenecaEastLSDTax\SenecaEastLSDTax::class,
        'Shelby CSD' => Appleton\Taxes\Countries\US\Ohio\ShelbyCSDTax\ShelbyCSDTax::class,
        'South Central LSD' => Appleton\Taxes\Countries\US\Ohio\SouthCentralLSDTax\SouthCentralLSDTax::class,
        'Southeastern LSD' => Appleton\Taxes\Countries\US\Ohio\SoutheasternLSDTax\SoutheasternLSDTax::class,
        'Southwest Licking LSD' => Appleton\Taxes\Countries\US\Ohio\SouthwestLickingLSDTax\SouthwestLickingLSDTax::class,
        'Southwest LSD' => Appleton\Taxes\Countries\US\Ohio\SouthwestLSDTax\SouthwestLSDTax::class,
        'Spencerville LSD' => Appleton\Taxes\Countries\US\Ohio\SpencervilleLSDTax\SpencervilleLSDTax::class,
        'Springfield LSD' => Appleton\Taxes\Countries\US\Ohio\SpringfieldLSDTax\SpringfieldLSDTax::class,
        'Stryker LSD' => Appleton\Taxes\Countries\US\Ohio\StrykerLSDTax\StrykerLSDTax::class,
        'Swanton LSD' => Appleton\Taxes\Countries\US\Ohio\SwantonLSDTax\SwantonLSDTax::class,
        'Talawanda CSD' => Appleton\Taxes\Countries\US\Ohio\TalawandaCSDTax\TalawandaCSDTax::class,
        'Teays Valley LSD' => Appleton\Taxes\Countries\US\Ohio\TeaysValleyLSDTax\TeaysValleyLSDTax::class,
        'Tri-County North LSD' => Appleton\Taxes\Countries\US\Ohio\TriCountyNorthLSDTax\TriCountyNorthLSDTax::class,
        'Tri-Village LSD' => Appleton\Taxes\Countries\US\Ohio\TriVillageLSDTax\TriVillageLSDTax::class,
        'Triad LSD' => Appleton\Taxes\Countries\US\Ohio\TriadLSDTax\TriadLSDTax::class,
        'Triway LSD' => Appleton\Taxes\Countries\US\Ohio\TriwayLSDTax\TriwayLSDTax::class,
        'Troy CSD' => Appleton\Taxes\Countries\US\Ohio\TroyCSDTax\TroyCSDTax::class,
        'Twin Valley Community LSD' =>
        Appleton\Taxes\Countries\US\Ohio\TwinValleyCommunityLSDTax\TwinValleyCommunityLSDTax::class,
        'Union-Scioto LSD' => Appleton\Taxes\Countries\US\Ohio\UnionSciotoLSDTax\UnionSciotoLSDTax::class,
        'United LSD' => Appleton\Taxes\Countries\US\Ohio\UnitedLSDTax\UnitedLSDTax::class,
        'Upper Sandusky EVSD' => Appleton\Taxes\Countries\US\Ohio\UpperSanduskyEVSDTax\UpperSanduskyEVSDTax::class,
        'Upper Scioto Valley LSD' => Appleton\Taxes\Countries\US\Ohio\UpperSciotoValleyLSDTax\UpperSciotoValleyLSDTax::class,
        'Valley View LSD' => Appleton\Taxes\Countries\US\Ohio\ValleyViewLSDTax\ValleyViewLSDTax::class,
        'Van Wert CSD' => Appleton\Taxes\Countries\US\Ohio\VanWertCSDTax\VanWertCSDTax::class,
        'Vanlue LSD' => Appleton\Taxes\Countries\US\Ohio\VanlueLSDTax\VanlueLSDTax::class,
        'Versailles EVSD' => Appleton\Taxes\Countries\US\Ohio\VersaillesEVSDTax\VersaillesEVSDTax::class,
        'Walnut Township LSD' => Appleton\Taxes\Countries\US\Ohio\WalnutTownshipLSDTax\WalnutTownshipLSDTax::class,
        'Wapakoneta CSD' => Appleton\Taxes\Countries\US\Ohio\WapakonetaCSDTax\WapakonetaCSDTax::class,
        'Wayne Trace LSD' => Appleton\Taxes\Countries\US\Ohio\WayneTraceLSDTax\WayneTraceLSDTax::class,
        'Waynesfield-Goshen LSD' => Appleton\Taxes\Countries\US\Ohio\WaynesfieldGoshenLSDTax\WaynesfieldGoshenLSDTax::class,
        'Wellington EVSD' => Appleton\Taxes\Countries\US\Ohio\WellingtonEVSDTax\WellingtonEVSDTax::class,
        'West Liberty-Salem LSD' => Appleton\Taxes\Countries\US\Ohio\WestLibertySalemLSDTax\WestLibertySalemLSDTax::class,
        'Western Reserve LSD' => Appleton\Taxes\Countries\US\Ohio\WesternReserveLSDTax\WesternReserveLSDTax::class,
        'Willard CSD' => Appleton\Taxes\Countries\US\Ohio\WillardCSDTax\WillardCSDTax::class,
        'Wilmington CSD' => Appleton\Taxes\Countries\US\Ohio\WilmingtonCSDTax\WilmingtonCSDTax::class,
        'Wyoming CSD' => Appleton\Taxes\Countries\US\Ohio\WyomingCSDTax\WyomingCSDTax::class,
        'Xenia Community CSD' => Appleton\Taxes\Countries\US\Ohio\XeniaCommunityCSDTax\XeniaCommunityCSDTax::class,
        'Yellow Springs EVSD' => Appleton\Taxes\Countries\US\Ohio\YellowSpringsEVSDTax\YellowSpringsEVSDTax::class,
        'Zane-Trace LSD' => Appleton\Taxes\Countries\US\Ohio\ZaneTraceLSDTax\ZaneTraceLSDTax::class,
    ];

    public function up()
    {
        $id = DB::table('governmental_unit_areas')->where('name', 'Ohio')->first()->id;

        foreach (self::CLASSES as $name) {
            $area_id = DB::table('governmental_unit_areas')->insertGetId([
                'name' => $name.', OH',
                'area' => $id,
            ]);

            $tax_id = DB::table('taxes')->insertGetId([
                'name' => $name.' Ohio Tax',
                'class' => self::CLASSES[$name],
            ]);

            DB::table('tax_areas')->insert([[
                'tax_id' => $tax_id,
                'work_governmental_unit_area_id' => $area_id,
                'based' => TaxArea::BASED_ON_WORK_LOCATION,
            ]]);
        }
    }
}
